#!/usr/bin/env bash

# References.
# https://docs.saltstack.com/en/latest/topics/tutorials/walkthrough_macosx.html

# We only set up a master on OS X if we are provisioning other systems with that master?

CURRENT_DIR=$(pwd)
SALT_CONFIG='/etc/salt'
STATE_TREE_ROOT='/srv'
PRIVATE_PILLAR="${CURRENT_DIR}/../pillar_private"

id -nG $(whoami) | grep -qw admin;
if test $? -ne 0; then
  echo "In order to install Homebrew, user ${USER} must be a member of the 'admin' group. BYE."
  exit 1
fi

if [ $(brew --version &> /dev/null; echo $?) -ne 0 ]; then
  echo "Install Homebrew."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  BREW_VERSION=$(brew --version)
  WHICH_BREW=$(which brew)
  echo "Homebrew found in ${WHICH_BREW}:"
  echo "${BREW_VERSION}"
fi

echo

if [ $(salt --version &> /dev/null; echo $?) -ne 0 ]; then
  echo "Install Salt."
  brew install saltstack
else
  SALT_VERSION=$(salt --version)
  echo "Found Salt already installed, version: ${SALT_VERSION}"
fi


if [ $(ls "${SALT_CONFIG}" &> /dev/null; echo $?) -eq 0 ]; then
  echo "Found an existing salt configuration in ${SALT_CONFIG}."

  read -p "DO YOU WANT TO REMOVE THE EXISTING CONFIGURATION (type Y to proceed) ?" -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]
  then
    echo "You chose to leave the existing Salt configuration intact."
    echo "To reset the existing configuration re-run bootstrap and choose yes instead."
    exit 1
  fi
fi

echo

echo "Remove existing configuration:"
sudo rm -rvf "${SALT_CONFIG}" "${STATE_TREE_ROOT}/pillar" "${STATE_TREE_ROOT}/salt"

echo

echo "Create configuration directory: ${SALT_CONFIG}."
sudo mkdir -p "${SALT_CONFIG}"
sudo chown "${USER}":everyone "${SALT_CONFIG}"

if test ! -d "${STATE_TREE_ROOT}"; then
  echo "Create state tree root directory: ${STATE_TREE_ROOT}."
  sudo mkdir -pv "${STATE_TREE_ROOT}"
  sudo chown "${USER}":everyone "${STATE_TREE_ROOT}"
fi

echo

# Set masterless minion configuration.
echo "Configure minion, pillars and states:"
ln -sfv "${CURRENT_DIR}/provisioners/salt/etc/minion" "${SALT_CONFIG}/minion"

# Set state tree.
ln -sfv "${CURRENT_DIR}/provisioners/salt/pillar" "${STATE_TREE_ROOT}/pillar"
ln -sfv "${CURRENT_DIR}/provisioners/salt/salt" "${STATE_TREE_ROOT}/salt"

# Link optional private pillar if found.
if test -d "${PRIVATE_PILLAR}"; then
  sudo ln -sfv "${PRIVATE_PILLAR}" "${STATE_TREE_ROOT}/pillar_private"
fi

echo "Bootstrap script finished."
